#!/bin/sh
usage="Usage: ./install [DESTDIR]\nDESTDIR - destination directory (default is /)"

if [ ! -z $2 ]; then
	echo "ERROR: Too many parameters!"
	echo
	echo -e $usage
	exit
fi

if [ ! -z $1 ]; then
	if [ $1 = "--help" ]; then
		echo -e $usage
		exit
	fi
fi

destdir="/"

if [ ! -z $1 ]; then
	if [ ! -e $1 ]; then
		echo "ERROR: Directory '$1' does not exist!"
		exit
	fi
	destdir=$1
fi

if [ ! -e $destdir/usr ]; then
	mkdir "$destdir/usr"
	chmod 755 "$destdir/usr"
fi

if [ ! -e $destdir/share ]; then
	mkdir "$destdir/usr/share"
	chmod 755 "$destdir/usr/share"
fi

if [ ! -e $destdir/share/stjerm ]; then
	mkdir "$destdir/usr/share/stjerm"
	chmod 755 "$destdir/usr/share/stjerm"
fi

if [ ! -e $destdir/usr/bin ]; then
	mkdir "$destdir/usr/bin"
	chmod 755 "$destdir/usr/bin"
fi

cp ./bin/stjerm.exe "$destdir/usr/share/stjerm/"
chmod 644 "$destdir/usr/share/stjerm/stjerm.exe"

cp ./README "$destdir/usr/share/stjerm/"
chmod 644 "$destdir/usr/share/stjerm/README"

cp ./data/stjerm.glade "$destdir/usr/share/stjerm/"
chmod 644 "$destdir/usr/share/stjerm/stjerm.glade"

echo -e "#!/bin/sh\nexec mono $destdir/usr/share/stjerm/stjerm.exe" > "$destdir/usr/bin/stjerm"
chmod 755 "$destdir/usr/bin/stjerm"

