#!/bin/sh
usage="Usage: ./install [PREFIX]\n\nPREFIX - prefix directory (default is /usr)\n\nWARNING: Do not use any relative paths as prefix!\nNOTE: Stjerm will install all it's files somewhere in PREFIX."

if [ ! -z $2 ]; then
	echo "ERROR: Too many parameters!"
	echo
	echo -e $usage
	exit
fi

if [ ! -z $1 ]; then
	if [ $1 = "--help" ]; then
		echo -e $usage
		exit
	fi
fi

prefix="/usr"

if [ ! -z $1 ]; then
	if [ ! -e $1 ]; then
		echo "ERROR: Directory '$1' does not exist!"
		exit
	fi
	prefix=$1
fi

if [ ! -e $prefix/share ]; then
	mkdir "$prefix/share"
	chmod 755 "$prefix/share"
fi

if [ ! -e $prefix/share/stjerm ]; then
	mkdir "$prefix/share/stjerm"
	chmod 755 "$prefix/share/stjerm"
fi

if [ ! -e $prefix/bin ]; then
	mkdir "$prefix/bin"
	chmod 755 "$prefix/bin"
fi

cp ./bin/stjerm.exe "$prefix/share/stjerm/"
chmod 644 "$prefix/share/stjerm/stjerm.exe"

cp ./README "$prefix/share/stjerm/"
chmod 644 "$prefix/share/stjerm/README"

echo -e "#!/bin/sh\nexec mono /$prefix/share/stjerm/stjerm.exe" > "$prefix/bin/stjerm"
chmod 755 "$prefix/bin/stjerm"

