#!/bin/sh
usage="Usage: ./uninstall [PREFIX]\n\nPREFIX - prefix directory (default is /usr)\n\nWARNING: Do not use any relative paths as prefix!\nWARNING: If you don't specify PREFIX, /usr will be used!"

if [ ! -z $2 ]; then
	echo "ERROR: Too many parameters!"
	echo
	echo -e $usage
	exit
fi

if [ ! -z $1 ]; then
	if [ $1 = "--help" ]; then
		echo -e $usage
		exit
	fi
fi

prefix="/usr"

if [ ! -z $1 ]; then
	if [ ! -e $1 ]; then
		echo "ERROR: Directory '$1' does not exist!"
		exit
	fi
	prefix=$1
fi

rm -rf "$prefix/share/stjerm"
rm -rf "$prefix/bin/stjerm"
