#!/bin/sh
usage="Usage: ./uninstall [SRCDIR]\nSRCDIR - source directory (default is /)."

if [ ! -z $2 ]; then
	echo "ERROR: Too many parameters!"
	echo
	echo -e $usage
	exit
fi

if [ ! -z $1 ]; then
	if [ $1 = "--help" ]; then
		echo -e $usage
		exit
	fi
fi

prefix="/usr"

if [ ! -z $1 ]; then
	if [ ! -e $1 ]; then
		echo "ERROR: Directory '$1' does not exist!"
		exit
	fi
	prefix=$1
fi

rm -rf "$prefix/usr/share/stjerm"
rm -rf "$prefix/usr/bin/stjerm"
