// Name: Config.cs
// Date: 2006 08 18
// Author: Stjepan Glavina
// Email: stjepang AT gmail DOT com
// 
// Copyright 2006 Stjepan Glavina
// 
// This file is part of Stjerm.
//
// Stjerm is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
// 
// Stjerm is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Stjerm; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

using System;
using System.IO;

namespace Stjerm
{
	public class Config
	{
		private string filename = "/home/" +
								  System.Environment.UserName.ToString() +
								  "/.stjermrc";
		private string[] options = new string[] {
									"sticky",
									"ontop",
									"showdeco"
		};
		private string[] defvalues = new string[] {
									"1",
									"1",
									"0"
		};
		
		public Config()
		{
			FileInfo fi = new FileInfo(filename);
			if (!fi.Exists || fi.Length < 20) // if doesn't exist or if empty
			{
				GenerateFile();
			}
		}
		
		public string GetOption(string opt)
		{
			string val = "";
			StreamReader sr = new StreamReader(filename);
			
			try
			{
				string line;
				while ((line = sr.ReadLine()) != null)
				{
					if (line.StartsWith(opt))
					{
						val = line.Substring(opt.Length + 1);
						break;
					}
				}
				
				if (val == "")
				{
					sr.Close();
					AddOption(opt);
				}
			}
			catch (Exception e)
			{
				Console.Error.WriteLine("ERROR: Can't read file " +
										filename.ToString() +
										"\nError message: " +
										e.Message);
				AppStjerm.Exit(2);
			}
			finally
			{
				sr.Close();
			}
			
			return val;
		}
		
		public void SetOption(string opt, string val)
		{
			string contents = "";
			
			StreamReader sr = new StreamReader(filename);
			try
			{
				string line;
				while ((line = sr.ReadLine()) != null)
				{
					if (line.StartsWith(opt))
					{
						contents += opt + "=" + val + "\n";
						continue;
					}
					contents += line + "\n";
				}
				
				if (val == "")
				{
					sr.Close();
					AddOption(opt);
					SetOption(opt, val);
					return;
				}
			}
			catch (Exception e)
			{
				Console.Error.WriteLine("ERROR: Can't read file " +
										filename.ToString() +
										"\nError message: " +
										e.Message);
				AppStjerm.Exit(2);
			}
			finally
			{
				sr.Close();
			}
			
			StreamWriter sw = new StreamWriter(filename, false);
			try
			{
				sw.Write(contents);
			}
			catch (Exception e)
			{
				Console.Error.WriteLine("ERROR: Can't write to file " +
										filename.ToString() +
										"\nError message: " +
										e.Message);
				AppStjerm.Exit(3);
			}
			finally
			{
				sw.Close();
			}
		}
		
		private void AddOption(string opt)
		{
			StreamWriter sw = new StreamWriter(filename, true);
			
			string contents = "";
			for (int i = 0; i < options.Length; i++)
			{
				if (options[i] == opt)
				{
					contents = opt + "=" + defvalues[i] + "\n";
					break;
				}
			}
			
			try
			{
				sw.Write(contents);
			}
			catch (Exception e)
			{
				Console.Error.WriteLine("ERROR: Can't write to file " +
										filename.ToString() +
										"\nError message: " +
										e.Message);
				AppStjerm.Exit(3);
			}
			finally
			{
				sw.Close();
			}
		}
		
		private void GenerateFile()
		{
			StreamWriter sw = new StreamWriter(filename, false);
			
			string opts = "";
			for (int i = 0; i < options.Length; i++)
			{
				opts += options[i] + "=" + defvalues[i] + "\n";
			}
			
			string contents = "# DO NOT EDIT THIS FILE! EDITING THIS FILE MAY CAUSE STJERM CRASH!\n" +
							   opts;
			try
			{
				sw.Write(contents);
			}
			catch (Exception e)
			{
				Console.Error.WriteLine("ERROR: Can't write to file " +
										filename.ToString() +
										"\nError message: " +
										e.Message);
				AppStjerm.Exit(2);
			}
			finally
			{
				sw.Close();
			}
		}
	}
}
