// Name: this.cs
// Date: 2006 08 18
// Author: Stjepan Glavina
// Email: stjepang AT gmail DOT com
// 
// Copyright 2006 Stjepan Glavina
// 
// This file is part of Stjerm.
//
// Stjerm is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
// 
// Stjerm is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Stjerm; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

using System;

namespace Stjerm
{
	public class Config
	{
		public enum Options
		{
			Sticky,
			AllWorkspaces,
			ShowDecoration
		};
		
		private string filename = "/home/" +
								  System.Environment.UserName.ToString() +
								  "/.stjermrc";
		
		public Config()
		{
			System.IO.FileInfo fi = new System.IO.FileInfo(this.filename);
			if (!fi.Exists || fi.Length < 5)
			{
				this.GenerateFile();
			}
		}
		
		private void GenerateFile()
		{
			System.IO.StreamWriter sw = new System.IO.StreamWriter(this.filename);
			string contents = "# DO NOT EDIT THIS FILE! EDITING THIS FILE MAY CAUSE STJERM CRASH!\n" +
							  "sticky=1\n" +
							  "allworkspaces=1\n" +
							  "showdeco=0\n";
			sw.Write(contents);
			sw.Close();
		}
	}
}
